spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/skibidiseat_prod
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true